// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBZFId5xkQDD8SHQ48-YtReeu_hL4nkbo',
    appId: '1:789379755544:web:158416513edeacf0badd6d',
    messagingSenderId: '789379755544',
    projectId: 'tripsapp-de2ce',
    authDomain: 'tripsapp-de2ce.firebaseapp.com',
    storageBucket: 'tripsapp-de2ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeLRmPe_9djC-TYgtj-W3HRjs6pCYkPg',
    appId: '1:789379755544:android:81c5a7bd95ca52b0badd6d',
    messagingSenderId: '789379755544',
    projectId: 'tripsapp-de2ce',
    storageBucket: 'tripsapp-de2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvTSRAm-SHhU7mdfyJ59cdiqWaDzJHNU',
    appId: '1:789379755544:ios:3efc5279719aa1e6badd6d',
    messagingSenderId: '789379755544',
    projectId: 'tripsapp-de2ce',
    storageBucket: 'tripsapp-de2ce.appspot.com',
    iosClientId: '789379755544-13u914t2h8984p4571b7dsfsia57u38c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBvTSRAm-SHhU7mdfyJ59cdiqWaDzJHNU',
    appId: '1:789379755544:ios:3efc5279719aa1e6badd6d',
    messagingSenderId: '789379755544',
    projectId: 'tripsapp-de2ce',
    storageBucket: 'tripsapp-de2ce.appspot.com',
    iosClientId: '789379755544-13u914t2h8984p4571b7dsfsia57u38c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
